modify gitignore, rename manifest, and update build script

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -6,25 +6,25 @@ BUILD_DIR='build'
 JAVAC_FLAGS=(-d "$BUILD_DIR")
 
 BIN_DIR='bin'
-JAR_NAME='Nexus.jar'
-MANIFEST_NAME='manifest.txt'
+JAR_PATH="$BIN_DIR/Nexus.jar"
+MANIFEST_PATH='META-INF/MANIFEST.MF'
 
-JAR_FLAGS=(cfm "$JAR_NAME" "$MANIFEST_NAME" -C "$BUILD_DIR" .)
+JAR_FLAGS=(cfm "$JAR_PATH" "$MANIFEST_PATH" -C "$BUILD_DIR" .)
 
-mkdir "$BUILD_DIR" "$BIN_DIR" 2>/dev/null
+mkdir "$BUILD_DIR" "$BIN_DIR" "${MANIFEST_PATH%/*}" 2>/dev/null
 
 SOURCES=()
 while read -r src; do
     SOURCES+=("$src")
 done < <(find "$SRC_DIR" -name '*.java')
 
-javac "${JAVAC_FLAGS[@]}" "${SOURCES[@]:?}" || {
-    echo 'failed to build classes!'
+javac "${JAVAC_FLAGS[@]}" "${SOURCES[@]:?'no java file found.'}" || {
+    echo 'failed to build classes.' >&2
     exit 1
 }
 
 jar "${JAR_FLAGS[@]}" || {
-    echo 'failed to create the jar'
+    echo 'failed to create the jar.' >&2
     exit 1
 }
 
